name: food_delivery_app
description: "Food Delivery App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  google_fonts: ^4.0.3
  responsive_framework: ^1.5.1


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
